FROM larryeitel/llp-php-fpm-70-ssh-supervisor:v4.0.4

MAINTAINER Larry Eitel <larry@eitel.com>

ARG INSTALL_MONGO=false
ENV INSTALL_MONGO ${INSTALL_MONGO}
ARG INSTALL_XDEBUG=true
ENV INSTALL_XDEBUG ${INSTALL_XDEBUG}

WORKDIR /var/www/laravel

# PHPStorm needs to see a php.ini
RUN touch /usr/local/etc/php/php.ini

ADD .dotfiles/.bashrc /root
COPY xdebug.ini /usr/local/etc/php/conf.d

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

EXPOSE 22 9000
